services:
  mongo1prod:
    image: mongo:latest
    hostname: mongo1prod
    container_name: mongo1prod
    networks:
      - localMongoProdNetwork
    ports:
      - 27021:27017
    entrypoint:
      [
        "mongod",
        "--replSet",
        "myProdReplicaSet",
        "--bind_ip",
        "localhost,127.0.0.1,mongo1prod"
      ]
  mongo2prod:
    image: mongo:latest
    hostname: mongo2prod
    container_name: mongo2prod
    networks:
      - localMongoProdNetwork
    ports:
      - 27022:27017
    entrypoint:
      [
        "mongod",
        "--replSet",
        "myProdReplicaSet",
        "--bind_ip",
        "localhost,127.0.0.1,mongo2prod"
      ]
  mongo3prod:
    image: mongo:latest
    hostname: mongo3prod
    container_name: mongo3prod
    networks:
      - localMongoProdNetwork
    ports:
      - 27023:27017
    entrypoint:
      [
        "mongod",
        "--replSet",
        "myProdReplicaSet",
        "--bind_ip",
        "localhost,127.0.0.1,mongo3prod"
      ]
  mongosetup-prod:
    image: mongo:latest
    networks:
      - localMongoProdNetwork
    depends_on:
      - mongo1prod
      - mongo2prod
      - mongo3prod
    volumes:
      - ./scripts:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh" ]

networks:
  localMongoProdNetwork:
    driver: bridge

volumes:
  mongo1_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\Users\Megz\Desktop\db\prod\mongo1
  mongo2_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\Users\Megz\Desktop\db\prod\mongo2
  mongo3_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\Users\Megz\Desktop\db\prod\mongo3
